<?php

namespace Database\Seeders;

use App\Models\Court;
use App\Models\Region;
use Illuminate\Database\Seeder;

class CourtSeeder extends Seeder
{
    public function run(): void
    {
        // Map regions to IDs
        $regions = Region::pluck('id', 'name')->toArray();

        $courts = [
            ['region_name' => 'Greater Accra', 'name' => 'Supreme Court', 'type' => 'Supreme Court', 'address' => 'Accra', 'code' => 'SC-001'],
            ['region_name' => 'Greater Accra', 'name' => 'Court of Appeal ( Civil & Criminal)', 'type' => 'Court of Appeal', 'address' => 'Accra', 'code' => 'COA-001'],
            ['region_name' => 'Greater Accra', 'name' => 'High Court - General Jurisdiction ( 1 – 13 )', 'type' => 'High Court', 'address' => 'Law Court Complex, Accra', 'code' => 'HC-001'],
            ['region_name' => 'Greater Accra', 'name' => 'High Court  - Criminal     (1 – 5 )', 'type' => 'High Court', 'address' => 'Law Court Complex, Accra', 'code' => 'HC-002'],
            ['region_name' => 'Greater Accra', 'name' => 'High Court - Probate & L. A  (1 – 3 )', 'type' => 'High Court', 'address' => 'Law Court Complex, Accra', 'code' => 'HC-003'],
            ['region_name' => 'Greater Accra', 'name' => 'High Court – Financial & Economic Crime    (1 & 2 )', 'type' => 'High Court', 'address' => 'Law Court Complex, Accra', 'code' => 'HC-004'],
            ['region_name' => 'Greater Accra', 'name' => 'High Court - Land (1 –11)', 'type' => 'High Court', 'address' => 'Law Court Complex, Accra', 'code' => 'HC-005'],
            ['region_name' => 'Greater Accra', 'name' => 'High Court –Commercial  ( 1- 10 )', 'type' => 'High Court', 'address' => 'Law Court Complex, Accra', 'code' => 'HC-006'],
            ['region_name' => 'Greater Accra', 'name' => 'High Court – Divorce & Matrimonial ( 1 – 3 )', 'type' => 'High Court', 'address' => 'Law Court Complex, Accra', 'code' => 'HC-007'],
            ['region_name' => 'Greater Accra', 'name' => 'High Court -  Human Rights ( 1 & 2 )', 'type' => 'High Court', 'address' => 'Law Court Complex, Accra', 'code' => 'HC-008'],
            ['region_name' => 'Greater Accra', 'name' => 'High Court – Industrial & Labour     ( 1 & 2 )', 'type' => 'High Court', 'address' => 'Law Court Complex, Accra', 'code' => 'HC-009'],
            ['region_name' => 'Greater Accra', 'name' => 'High Court ( A & B )', 'type' => 'High Court', 'address' => 'Tema', 'code' => 'HC-010'],
            ['region_name' => 'Greater Accra', 'name' => 'High Court -Land ( 1& 2)', 'type' => 'High Court', 'address' => 'Tema', 'code' => 'HC-011'],
            ['region_name' => 'Greater Accra', 'name' => 'High  Court (1 & 2)', 'type' => 'High Court', 'address' => 'Adentan', 'code' => 'HC-012'],
            ['region_name' => 'Greater Accra', 'name' => 'High   Court', 'type' => 'High Court', 'address' => 'Amasaman', 'code' => 'HC-013'],
            ['region_name' => 'Greater Accra', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Sowutuom', 'code' => 'HC-014'],
            ['region_name' => 'Greater Accra', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Gbetsele', 'code' => 'HC-015'],
            ['region_name' => 'Greater Accra', 'name' => 'Circuit Court ( 1  - 11 )', 'type' => 'Circuit Court', 'address' => 'Accra', 'code' => 'CC-001'],
            ['region_name' => 'Greater Accra', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Amasaman', 'code' => 'CC-002'],
            ['region_name' => 'Greater Accra', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Kwabenya', 'code' => 'CC-003'],
            ['region_name' => 'Greater Accra', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Weija', 'code' => 'CC-004'],
            ['region_name' => 'Greater Accra', 'name' => 'Circuit Court ( A & B )', 'type' => 'Circuit Court', 'address' => 'Tema', 'code' => 'CC-005'],
            ['region_name' => 'Greater Accra', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Ashaiman', 'code' => 'CC-006'],
            ['region_name' => 'Greater Accra', 'name' => 'Circuit Court (1 & 2 )', 'type' => 'Circuit Court', 'address' => 'Adentan', 'code' => 'CC-007'],
            ['region_name' => 'Greater Accra', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Dorvsu, Police HQ', 'code' => 'CC-008'],
            ['region_name' => 'Greater Accra', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Dansoman', 'code' => 'CC-009'],
            ['region_name' => 'Greater Accra', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Achimota', 'code' => 'CC-010'],
            ['region_name' => 'Greater Accra', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Gbetsele', 'code' => 'CC-011'],
            ['region_name' => 'Greater Accra', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Ada', 'code' => 'CC-012'],
            ['region_name' => 'Greater Accra', 'name' => 'Family & Juvenile Court     ( A – C )', 'type' => 'Family & Juvenile Court', 'address' => 'Accra', 'code' => 'FJC-001'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Adjabeng', 'code' => 'DC-001'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Abeka', 'code' => 'DC-002'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Ashaiman', 'code' => 'DC-003'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court (1 & 2 )', 'type' => 'District Court', 'address' => 'Adentan', 'code' => 'DC-004'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court (1 & 2 )', 'type' => 'District Court', 'address' => 'Kaneshie', 'code' => 'DC-005'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court ( A & B )', 'type' => 'District Court', 'address' => 'Madina', 'code' => 'DC-006'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court ( A & B )', 'type' => 'District Court', 'address' => 'Amasaman', 'code' => 'DC-007'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Dodowa', 'code' => 'DC-008'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Weija', 'code' => 'DC-009'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'La', 'code' => 'DC-010'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court (1 & 2 )', 'type' => 'District Court', 'address' => 'Tema', 'code' => 'DC-011'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Ada', 'code' => 'DC-012'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Prampram', 'code' => 'DC-013'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Sege', 'code' => 'DC-014'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Teshie', 'code' => 'DC-015'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court, TDC', 'type' => 'District Court', 'address' => 'Tema', 'code' => 'DC-016'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Sowutuom', 'code' => 'DC-017'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Dorvsu, Police HQ', 'code' => 'DC-018'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Asofan – Ofankor', 'code' => 'DC-019'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Ngleshie Amanfro', 'code' => 'DC-020'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Gbese', 'code' => 'DC-021'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Baatsonaa', 'code' => 'DC-022'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kotobabi', 'code' => 'DC-023'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'SSNIT ( 1-3), Accra', 'code' => 'DC-024'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Bills (1-4),Accra,Saturday', 'code' => 'DC-025'],
            ['region_name' => 'Greater Accra', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Bills (1-4), Accra Afternoons', 'code' => 'DC-026'],
            ['region_name' => 'Eastern', 'name' => 'Court of Appeal', 'type' => 'Court of Appeal', 'address' => 'Koforidua', 'code' => 'COA-002'],
            ['region_name' => 'Eastern', 'name' => 'High Court – General         ( 1 & 3 )', 'type' => 'High Court', 'address' => 'Koforidua', 'code' => 'HC-016'],
            ['region_name' => 'Eastern', 'name' => 'High Court – Commercial (2 & 4 )', 'type' => 'High Court', 'address' => 'Koforidua', 'code' => 'HC-017'],
            ['region_name' => 'Eastern', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Akim Oda', 'code' => 'HC-018'],
            ['region_name' => 'Eastern', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Nkawkaw', 'code' => 'HC-019'],
            ['region_name' => 'Eastern', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Nsawam', 'code' => 'HC-020'],
            ['region_name' => 'Eastern', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Nsawam  ( Prisons )', 'code' => 'HC-021'],
            ['region_name' => 'Eastern', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Somanya', 'code' => 'HC-022'],
            ['region_name' => 'Eastern', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Kyebi', 'code' => 'HC-023'],
            ['region_name' => 'Eastern', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Odumase Krobo', 'code' => 'HC-024'],
            ['region_name' => 'Eastern', 'name' => 'Circuit Court – (A & B )', 'type' => 'Circuit Court', 'address' => 'Koforidua', 'code' => 'CC-013'],
            ['region_name' => 'Eastern', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Nsawam', 'code' => 'CC-014'],
            ['region_name' => 'Eastern', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Asamankese', 'code' => 'CC-015'],
            ['region_name' => 'Eastern', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Akim Swedru', 'code' => 'CC-016'],
            ['region_name' => 'Eastern', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Mpraeso', 'code' => 'CC-017'],
            ['region_name' => 'Eastern', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Odumase Krobo', 'code' => 'CC-018'],
            ['region_name' => 'Eastern', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Akropong-Akwapim', 'code' => 'CC-019'],
            ['region_name' => 'Eastern', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Suhum', 'code' => 'CC-020'],
            ['region_name' => 'Eastern', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Anyinam', 'code' => 'CC-021'],
            ['region_name' => 'Eastern', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Kyebi', 'code' => 'CC-022'],
            ['region_name' => 'Eastern', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Nkwatia', 'code' => 'CC-023'],
            ['region_name' => 'Eastern', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'New Abriem', 'code' => 'CC-024'],
            ['region_name' => 'Eastern', 'name' => 'District Court – ( A & B )', 'type' => 'District Court', 'address' => 'Koforidua', 'code' => 'DC-027'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Begoro', 'code' => 'DC-028'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Nkawkaw', 'code' => 'DC-029'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Akim Ofoase', 'code' => 'DC-030'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Abetifi', 'code' => 'DC-031'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Donkorkrom', 'code' => 'DC-032'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kyebi', 'code' => 'DC-033'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Nsawam', 'code' => 'DC-034'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Mampong-Akwapim', 'code' => 'DC-035'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kwabeng', 'code' => 'DC-036'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Asamankese', 'code' => 'DC-037'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Akim Oda', 'code' => 'DC-038'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Asesewa', 'code' => 'DC-039'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Senchi Ferry', 'code' => 'DC-040'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Somanya', 'code' => 'DC-041'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kade', 'code' => 'DC-042'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Suhum', 'code' => 'DC-043'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'New Tafo', 'code' => 'DC-044'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'New Abirim', 'code' => 'DC-045'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Aburi', 'code' => 'DC-046'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Osino', 'code' => 'DC-047'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kra Aboa Coaltar', 'code' => 'DC-048'],
            ['region_name' => 'Eastern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Akwatia', 'code' => 'DC-049'],
            ['region_name' => 'Central', 'name' => 'High Court – General       (1 -3 )', 'type' => 'High Court', 'address' => 'Cape Coast', 'code' => 'HC-025'],
            ['region_name' => 'Central', 'name' => 'High Court – Commercial ( A & B )', 'type' => 'High Court', 'address' => 'Cape Coast', 'code' => 'HC-026'],
            ['region_name' => 'Central', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Agona Swedru', 'code' => 'HC-027'],
            ['region_name' => 'Central', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Dunkwa-On-Offin', 'code' => 'HC-028'],
            ['region_name' => 'Central', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Winneba', 'code' => 'HC-029'],
            ['region_name' => 'Central', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Mankesim', 'code' => 'HC-030'],
            ['region_name' => 'Central', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Assin Fosu', 'code' => 'HC-031'],
            ['region_name' => 'Central', 'name' => 'High Court (1&2)', 'type' => 'High Court', 'address' => 'Kasoa Odupong Kpehe', 'code' => 'HC-032'],
            ['region_name' => 'Central', 'name' => 'Circuit Court ( 1 &2 )', 'type' => 'Circuit Court', 'address' => 'Cape Coast', 'code' => 'CC-025'],
            ['region_name' => 'Central', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Agona Swedru', 'code' => 'CC-026'],
            ['region_name' => 'Central', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Dunkwa-On-Offin', 'code' => 'CC-027'],
            ['region_name' => 'Central', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Ofaakor', 'code' => 'CC-028'],
            ['region_name' => 'Central', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Mankesim', 'code' => 'CC-029'],
            ['region_name' => 'Central', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Nsuaem Kyekyewere', 'code' => 'CC-030'],
            ['region_name' => 'Central', 'name' => 'District Court ( 1 & 2 )', 'type' => 'District Court', 'address' => 'Cape Coast', 'code' => 'DC-050'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Agona - Swedru', 'code' => 'DC-051'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Winneba', 'code' => 'DC-052'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Awutu', 'code' => 'DC-053'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Saltpond', 'code' => 'DC-054'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Apam', 'code' => 'DC-055'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Dawurampong', 'code' => 'DC-056'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Breman - Asikuma', 'code' => 'DC-057'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Ajumako', 'code' => 'DC-058'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Twifo Praso', 'code' => 'DC-059'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Dunkwa-On-Offin', 'code' => 'DC-060'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Elmina', 'code' => 'DC-061'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Abura-Dunkwa', 'code' => 'DC-062'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Essarkyir', 'code' => 'DC-063'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Nyankomasi Ahenkro', 'code' => 'DC-064'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kasoa', 'code' => 'DC-065'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Ofaakor', 'code' => 'DC-066'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Diaso', 'code' => 'DC-067'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Assin Foso', 'code' => 'DC-068'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Mankesim', 'code' => 'DC-069'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Twifo Hemang', 'code' => 'DC-070'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Gomoa Afransi', 'code' => 'DC-071'],
            ['region_name' => 'Central', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Agona Nsabaa', 'code' => 'DC-072'],
            ['region_name' => 'Western', 'name' => 'Court of Appeal', 'type' => 'Court of Appeal', 'address' => 'Sekondi', 'code' => 'COA-003'],
            ['region_name' => 'Western', 'name' => 'High Court – General         ( 1 – 3 )', 'type' => 'High Court', 'address' => 'Sekondi', 'code' => 'HC-033'],
            ['region_name' => 'Western', 'name' => 'High Court – Commercial         ( A & B )', 'type' => 'High Court', 'address' => 'Sekondi', 'code' => 'HC-034'],
            ['region_name' => 'Western', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Tarkwa', 'code' => 'HC-035'],
            ['region_name' => 'Western', 'name' => 'Circuit Court ( A & B)', 'type' => 'Circuit Court', 'address' => 'Takoradi', 'code' => 'CC-031'],
            ['region_name' => 'Western', 'name' => 'Circuit Court ( Gender & DV)', 'type' => 'Circuit Court', 'address' => 'Sekondi', 'code' => 'CC-032'],
            ['region_name' => 'Western', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Tarkwa', 'code' => 'CC-033'],
            ['region_name' => 'Western', 'name' => 'District Court  ( A & B )', 'type' => 'District Court', 'address' => 'Sekondi', 'code' => 'DC-073'],
            ['region_name' => 'Western', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Takoradi Market Circle', 'code' => 'DC-074'],
            ['region_name' => 'Western', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Takoradi Harbour Area', 'code' => 'DC-075'],
            ['region_name' => 'Western', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Agona-Nkwanta', 'code' => 'DC-076'],
            ['region_name' => 'Western', 'name' => 'District Court', 'type' => 'District Court', 'address' => '*Axim* (Converted to C/C)', 'code' => 'DC-077'],
            ['region_name' => 'Western', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Nkroful', 'code' => 'DC-078'],
            ['region_name' => 'Western', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Half Assini', 'code' => 'DC-079'],
            ['region_name' => 'Western', 'name' => 'District Court ( A & B )', 'type' => 'District Court', 'address' => 'Tarkwa', 'code' => 'DC-080'],
            ['region_name' => 'Western', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Prestea', 'code' => 'DC-081'],
            ['region_name' => 'Western', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Shama', 'code' => 'DC-082'],
            ['region_name' => 'Western', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Daboase', 'code' => 'DC-083'],
            ['region_name' => 'Western', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Asankragwa', 'code' => 'DC-084'],
            ['region_name' => 'Western', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Wassa-Akropong', 'code' => 'DC-085'],
            ['region_name' => 'Western', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kwesimintsim', 'code' => 'DC-086'],
            ['region_name' => 'Western', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Mpohor', 'code' => 'DC-087'],
            ['region_name' => 'Western North', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Sefwi-Wiawso', 'code' => 'HC-036'],
            ['region_name' => 'Western North', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Bibiani', 'code' => 'CC-034'],
            ['region_name' => 'Western North', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Enchi', 'code' => 'CC-035'],
            ['region_name' => 'Western North', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Bodi', 'code' => 'CC-036'],
            ['region_name' => 'Western North', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Enchi', 'code' => 'DC-088'],
            ['region_name' => 'Western North', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Bibiani', 'code' => 'DC-089'],
            ['region_name' => 'Western North', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Debiso', 'code' => 'DC-090'],
            ['region_name' => 'Western North', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Juaboso', 'code' => 'DC-091'],
            ['region_name' => 'Western North', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Sefwi-Wiawso', 'code' => 'DC-092'],
            ['region_name' => 'Western North', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Akotombra', 'code' => 'DC-093'],
            ['region_name' => 'Western North', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Adabokrom', 'code' => 'DC-094'],
            ['region_name' => 'Ashanti', 'name' => 'Court of Appeal', 'type' => 'Court of Appeal', 'address' => 'Kumasi', 'code' => 'COA-004'],
            ['region_name' => 'Ashanti', 'name' => 'High Court – General        (1 -  3 )', 'type' => 'High Court', 'address' => 'Kumasi', 'code' => 'HC-037'],
            ['region_name' => 'Ashanti', 'name' => 'High Court – Land ( 1 – 4 )', 'type' => 'High Court', 'address' => 'Kumasi', 'code' => 'HC-038'],
            ['region_name' => 'Ashanti', 'name' => 'High Court -  Human Rights & Economic Crimes', 'type' => 'High Court', 'address' => 'Kumasi', 'code' => 'HC-039'],
            ['region_name' => 'Ashanti', 'name' => 'High Court -   Commercial       ( 1 & 2 )', 'type' => 'High Court', 'address' => 'Kumasi', 'code' => 'HC-040'],
            ['region_name' => 'Ashanti', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Kumasi  (Prisons)', 'code' => 'HC-041'],
            ['region_name' => 'Ashanti', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Mampong-Ashanti', 'code' => 'HC-042'],
            ['region_name' => 'Ashanti', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Obuasi', 'code' => 'HC-043'],
            ['region_name' => 'Ashanti', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Offinso', 'code' => 'HC-044'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court ( 1 – 4 )', 'type' => 'Circuit Court', 'address' => 'Adum - Kumasi', 'code' => 'CC-037'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'KMA - Kumasi', 'code' => 'CC-038'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Nkawie', 'code' => 'CC-039'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Kumawu', 'code' => 'CC-040'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Juaso', 'code' => 'CC-041'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Nsuta', 'code' => 'CC-042'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Obuasi', 'code' => 'CC-043'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Bekwai', 'code' => 'CC-044'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Offinso', 'code' => 'CC-045'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Tepa', 'code' => 'CC-046'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Juaben', 'code' => 'CC-047'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Akropong  Ashanti', 'code' => 'CC-048'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Old Tafo', 'code' => 'CC-049'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court (1&2)', 'type' => 'Circuit Court', 'address' => 'Asokwa', 'code' => 'CC-050'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Atasemanso', 'code' => 'CC-051'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Abuakwa', 'code' => 'CC-052'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Kwadaso', 'code' => 'CC-053'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Donyina', 'code' => 'CC-054'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court “1”', 'type' => 'Circuit Court', 'address' => 'Bills, Asokwa, Afternoon', 'code' => 'CC-055'],
            ['region_name' => 'Ashanti', 'name' => 'Circuit Court “2”', 'type' => 'Circuit Court', 'address' => 'Bills, Asokwa, Afternoon', 'code' => 'CC-056'],
            ['region_name' => 'Ashanti', 'name' => 'District Court ( 1 & 2 )', 'type' => 'District Court', 'address' => 'Prempeh Ass Hall - Kumasi', 'code' => 'DC-095'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Bekwai', 'code' => 'DC-096'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Obuasi', 'code' => 'DC-097'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'New Edubiase', 'code' => 'DC-098'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kuntanase', 'code' => 'DC-099'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Ejisu', 'code' => 'DC-100'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Ejura', 'code' => 'DC-101'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Agona-Ashanti', 'code' => 'DC-102'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Mampong-Ashanti', 'code' => 'DC-103'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Fomena', 'code' => 'DC-104'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Agogo', 'code' => 'DC-105'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Effiduase', 'code' => 'DC-106'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Tepa', 'code' => 'DC-107'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kodie', 'code' => 'DC-108'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Mankranso', 'code' => 'DC-109'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Nyinahin', 'code' => 'DC-110'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Offinso', 'code' => 'DC-111'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Konongo', 'code' => 'DC-112'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Manso Nkwanta', 'code' => 'DC-113'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Mamponteng', 'code' => 'DC-114'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Asokore Mampong', 'code' => 'DC-115'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Jacobu', 'code' => 'DC-116'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Akomadan', 'code' => 'DC-117'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Twedie', 'code' => 'DC-118'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kwaso', 'code' => 'DC-119'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Akropong-Ashanti', 'code' => 'DC-120'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Asiwa', 'code' => 'DC-121'],
            ['region_name' => 'Ashanti', 'name' => 'District Court ( 1 – 4 )', 'type' => 'District Court', 'address' => 'Asokwa', 'code' => 'DC-122'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Manso Adubia', 'code' => 'DC-123'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Toase', 'code' => 'DC-124'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Pakyi No. 2', 'code' => 'DC-125'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Bonwire', 'code' => 'DC-126'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Bompata', 'code' => 'DC-127'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Boamang', 'code' => 'DC-128'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Drobonso', 'code' => 'DC-129'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Wiamoase', 'code' => 'DC-130'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Pokukrom', 'code' => 'DC-131'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Ntonso', 'code' => 'DC-132'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Suame', 'code' => 'DC-133'],
            ['region_name' => 'Ashanti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Adansi Asokwa', 'code' => 'DC-134'],
            ['region_name' => 'Ashanti', 'name' => 'Bills (1&2) Ksi, Saturdays', 'type' => 'District Court', 'address' => 'Kumasi', 'code' => 'DC-135'],
            ['region_name' => 'Bono', 'name' => 'High Court – General        (1 – 3 )', 'type' => 'High Court', 'address' => 'Sunyani', 'code' => 'HC-045'],
            ['region_name' => 'Bono', 'name' => 'High Court – Commercial ( 1 & 2 )', 'type' => 'High Court', 'address' => 'Sunyani', 'code' => 'HC-046'],
            ['region_name' => 'Bono', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Wenchi', 'code' => 'HC-047'],
            ['region_name' => 'Bono', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Sunyani', 'code' => 'CC-057'],
            ['region_name' => 'Bono', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Fiapre', 'code' => 'CC-058'],
            ['region_name' => 'Bono', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Berekum', 'code' => 'CC-059'],
            ['region_name' => 'Bono', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Dormaa Ahenkro', 'code' => 'CC-060'],
            ['region_name' => 'Bono', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Wenchi', 'code' => 'CC-061'],
            ['region_name' => 'Bono', 'name' => 'District Court ( A & B )', 'type' => 'District Court', 'address' => 'Sunyani', 'code' => 'DC-136'],
            ['region_name' => 'Bono', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Drobo', 'code' => 'DC-137'],
            ['region_name' => 'Bono', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Wamfie', 'code' => 'DC-138'],
            ['region_name' => 'Bono', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Wenchi', 'code' => 'DC-139'],
            ['region_name' => 'Bono', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Berekum', 'code' => 'DC-140'],
            ['region_name' => 'Bono', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Sampa', 'code' => 'DC-141'],
            ['region_name' => 'Bono', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Nsoatre', 'code' => 'DC-142'],
            ['region_name' => 'Bono', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Nkrankwanta', 'code' => 'DC-143'],
            ['region_name' => 'Ahafo', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Duayaw Nkwanta', 'code' => 'CC-062'],
            ['region_name' => 'Ahafo', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Goaso', 'code' => 'CC-063'],
            ['region_name' => 'Ahafo', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Hwidiem', 'code' => 'CC-064'],
            ['region_name' => 'Ahafo', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Duayaw Nkwanta', 'code' => 'DC-144'],
            ['region_name' => 'Ahafo', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Goaso', 'code' => 'DC-145'],
            ['region_name' => 'Ahafo', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kukuom', 'code' => 'DC-146'],
            ['region_name' => 'Ahafo', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Bechem', 'code' => 'DC-147'],
            ['region_name' => 'Ahafo', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kenyasi', 'code' => 'DC-148'],
            ['region_name' => 'Bono East', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Atebubu ( Vacant)', 'code' => 'HC-048'],
            ['region_name' => 'Bono East', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Kintampo', 'code' => 'CC-065'],
            ['region_name' => 'Bono East', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Techiman', 'code' => 'CC-066'],
            ['region_name' => 'Bono East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Nkoranza', 'code' => 'DC-149'],
            ['region_name' => 'Bono East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Atebubu', 'code' => 'DC-150'],
            ['region_name' => 'Bono East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kwame Danso', 'code' => 'DC-151'],
            ['region_name' => 'Bono East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kintampo', 'code' => 'DC-152'],
            ['region_name' => 'Bono East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Tuobodom', 'code' => 'DC-153'],
            ['region_name' => 'Bono East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Yeji', 'code' => 'DC-154'],
            ['region_name' => 'Bono East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Jema', 'code' => 'DC-155'],
            ['region_name' => 'Volta', 'name' => 'High Court –  (1 - 3 )', 'type' => 'High Court', 'address' => 'Ho', 'code' => 'HC-049'],
            ['region_name' => 'Volta', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Denu', 'code' => 'HC-050'],
            ['region_name' => 'Volta', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Hohoe', 'code' => 'HC-051'],
            ['region_name' => 'Volta', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Sogakope', 'code' => 'HC-052'],
            ['region_name' => 'Volta', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Ho', 'code' => 'CC-067'],
            ['region_name' => 'Volta', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Hohoe', 'code' => 'CC-068'],
            ['region_name' => 'Volta', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Sogakope', 'code' => 'CC-069'],
            ['region_name' => 'Volta', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Keta', 'code' => 'CC-070'],
            ['region_name' => 'Volta', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Kpando', 'code' => 'CC-071'],
            ['region_name' => 'Volta', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Denu', 'code' => 'CC-072'],
            ['region_name' => 'Volta', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Juapong', 'code' => 'CC-073'],
            ['region_name' => 'Volta', 'name' => 'District Court ( 1 & 2 )', 'type' => 'District Court', 'address' => 'Ho', 'code' => 'DC-156'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Hohoe', 'code' => 'DC-157'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kpando', 'code' => 'DC-158'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Agbozume', 'code' => 'DC-159'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Adidome', 'code' => 'DC-160'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Dzodze', 'code' => 'DC-161'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Anloga', 'code' => 'DC-162'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Abor', 'code' => 'DC-163'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Peki', 'code' => 'DC-164'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Akatsi', 'code' => 'DC-165'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Dabala', 'code' => 'DC-166'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Ave Dakpa', 'code' => 'DC-167'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Vakpo', 'code' => 'DC-168'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Dzolokpuita', 'code' => 'DC-169'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kpetoe', 'code' => 'DC-170'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Adaklu', 'code' => 'DC-171'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Ve-Golokuati', 'code' => 'DC-172'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Nogokpo (Formerly Aflao)', 'code' => 'DC-173'],
            ['region_name' => 'Volta', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Battor', 'code' => 'DC-174'],
            ['region_name' => 'Oti', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Dambai', 'code' => 'HC-053'],
            ['region_name' => 'Oti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Jasikan', 'code' => 'CC-074'],
            ['region_name' => 'Oti', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Dambai', 'code' => 'CC-075'],
            ['region_name' => 'Oti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Jasikan', 'code' => 'DC-175'],
            ['region_name' => 'Oti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'New Ayoma', 'code' => 'DC-176'],
            ['region_name' => 'Oti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kadjebi', 'code' => 'DC-177'],
            ['region_name' => 'Oti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kete Krachi', 'code' => 'DC-178'],
            ['region_name' => 'Oti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Nkwanta', 'code' => 'DC-179'],
            ['region_name' => 'Oti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Dambai', 'code' => 'DC-180'],
            ['region_name' => 'Oti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kpassa', 'code' => 'DC-181'],
            ['region_name' => 'Oti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Chinderi', 'code' => 'DC-182'],
            ['region_name' => 'Oti', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Bonwire Kwamekrom', 'code' => 'DC-183'],
            ['region_name' => 'Northern', 'name' => 'Court of Appeal', 'type' => 'Court of Appeal', 'address' => 'Tamale', 'code' => 'COA-005'],
            ['region_name' => 'Northern', 'name' => 'High Court – General         (1 & 2 )', 'type' => 'High Court', 'address' => 'Tamale', 'code' => 'HC-054'],
            ['region_name' => 'Northern', 'name' => 'High Court – Commercial        (1 & 2 )', 'type' => 'High Court', 'address' => 'Tamale', 'code' => 'HC-055'],
            ['region_name' => 'Northern', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Tamale (Prisons)', 'code' => 'HC-056'],
            ['region_name' => 'Northern', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Tamale', 'code' => 'CC-076'],
            ['region_name' => 'Northern', 'name' => 'Circuit Court (Gender)', 'type' => 'Circuit Court', 'address' => 'Tamale', 'code' => 'CC-077'],
            ['region_name' => 'Northern', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Yendi', 'code' => 'CC-078'],
            ['region_name' => 'Northern', 'name' => 'District Court ( 1 & 2 )', 'type' => 'District Court', 'address' => 'Tamale', 'code' => 'DC-184'],
            ['region_name' => 'Northern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Bimbilla', 'code' => 'DC-185'],
            ['region_name' => 'Northern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Wulensi', 'code' => 'DC-186'],
            ['region_name' => 'Northern', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Kpandai', 'code' => 'DC-187'],
            ['region_name' => 'Savannah', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Damango', 'code' => 'HC-057'],
            ['region_name' => 'Savannah', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Damango', 'code' => 'CC-079'],
            ['region_name' => 'Savannah', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Bole', 'code' => 'DC-188'],
            ['region_name' => 'Savannah', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Salaga', 'code' => 'DC-189'],
            ['region_name' => 'North East', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Nalerigu', 'code' => 'HC-058'],
            ['region_name' => 'North East', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Nalerigu', 'code' => 'CC-080'],
            ['region_name' => 'North East', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Walewale', 'code' => 'CC-081'],
            ['region_name' => 'North East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Walewale', 'code' => 'DC-190'],
            ['region_name' => 'North East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Nalerigu', 'code' => 'DC-191'],
            ['region_name' => 'North East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Gambaga', 'code' => 'DC-192'],
            ['region_name' => 'North East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Chereponi', 'code' => 'DC-193'],
            ['region_name' => 'North East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Yagaba', 'code' => 'DC-194'],
            ['region_name' => 'Upper East', 'name' => 'High Court ( 1 & 2 )', 'type' => 'High Court', 'address' => 'Bolgatanga', 'code' => 'HC-059'],
            ['region_name' => 'Upper East', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Bolgatanga', 'code' => 'CC-082'],
            ['region_name' => 'Upper East', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Bawku', 'code' => 'CC-083'],
            ['region_name' => 'Upper East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Bolgatanga', 'code' => 'DC-195'],
            ['region_name' => 'Upper East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Bawku', 'code' => 'DC-196'],
            ['region_name' => 'Upper East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Navrongo', 'code' => 'DC-197'],
            ['region_name' => 'Upper East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Bongo', 'code' => 'DC-198'],
            ['region_name' => 'Upper East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Sandema', 'code' => 'DC-199'],
            ['region_name' => 'Upper East', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Zebilla', 'code' => 'DC-200'],
            ['region_name' => 'Upper East', 'name' => 'District  Court', 'type' => 'Other', 'address' => 'Garu', 'code' => 'O-001'],
            ['region_name' => 'Upper East', 'name' => 'District  Court', 'type' => 'Other', 'address' => 'Pusiga', 'code' => 'O-002'],
            ['region_name' => 'Upper East', 'name' => 'District  Court', 'type' => 'Other', 'address' => 'Zuarungu', 'code' => 'O-003'],
            ['region_name' => 'Upper West', 'name' => 'High Court', 'type' => 'High Court', 'address' => 'Wa', 'code' => 'HC-060'],
            ['region_name' => 'Upper West', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Wa', 'code' => 'CC-084'],
            ['region_name' => 'Upper West', 'name' => 'Circuit Court', 'type' => 'Circuit Court', 'address' => 'Lawra', 'code' => 'CC-085'],
            ['region_name' => 'Upper West', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Wa', 'code' => 'DC-201'],
            ['region_name' => 'Upper West', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Tumu', 'code' => 'DC-202'],
            ['region_name' => 'Upper West', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Jirapa', 'code' => 'DC-203'],
            ['region_name' => 'Upper West', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Nandom', 'code' => 'DC-204'],
            ['region_name' => 'Upper West', 'name' => 'District Court', 'type' => 'District Court', 'address' => 'Nadowli', 'code' => 'DC-205'],
        ];

        $totalNew = 0;
        $totalUpd = 0;
        foreach ($courts as $c) {
            if (!isset($regions[$c['region_name']])) {
                $this->command->warn('Region not found: ' . $c['region_name']);
                continue;
            }
            
            $exists = Court::where('code', $c['code'])->exists();
            
            Court::updateOrCreate(
                ['code' => $c['code']],
                [
                    'name' => $c['name'],
                    'type' => $c['type'],
                    'region_id' => $regions[$c['region_name']],
                    'address' => $c['address'],
                    'is_active' => true
                ]
            );
            
            $exists ? $totalUpd++ : $totalNew++;
        }

        $this->command->info("Court Seeding Completed.");
        $this->command->info("New Courts: $totalNew");
        $this->command->info("Updated Courts: $totalUpd");
    }
}