<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Role;

/**
 * Emails auto-generated from names (first.last@jsg.gov.gh).
 * Known existing accounts are matched by email via updateOrCreate.
 * Default password : Jsg@Judge2025!
 * Password reset   : required on first login
 */
class JudgeSeeder extends Seeder
{
    public function run(): void
    {
        $courtLevels = [
            [
                'level'  => 'Supreme Court',
                'judges' => [
                ['name'=>'Paul Baffoe Bonnie','email'=>'paul.baffoe-bonnie@jsg.gov.gh','emp_id'=>'SC-001'],
                ['name'=>'Gabriel Pwamang','email'=>'gabriel.pwamang@jsg.gov.gh','emp_id'=>'SC-002'],
                ['name'=>'Avril Lovelace Johnson','email'=>'avril.johnson@jsg.gov.gh','emp_id'=>'SC-003'],
                ['name'=>'Issifu Omoro Tanko Amadu','email'=>'tanko.amadu@jsg.gov.gh','emp_id'=>'SC-004'],
                ['name'=>'Henrietta Joy Abena Nyarko Mensa-Bonsu','email'=>'henrietta.mensa-bonsu@jsg.gov.gh','emp_id'=>'SC-005'],
                ['name'=>'Emmanuel Yonny Kulendi','email'=>'emmanuel.kulendi@jsg.gov.gh','emp_id'=>'SC-006'],
                ['name'=>'Samuel Kwame Adibu-Asiedu','email'=>'samuel.adibu-asiedu@jsg.gov.gh','emp_id'=>'SC-007'],
                ['name'=>'George Kingsley Koomson','email'=>'george.koomson@jsg.gov.gh','emp_id'=>'SC-008'],
                ['name'=>'Ernest Yao Gaewu','email'=>'ernest.gaewu@jsg.gov.gh','emp_id'=>'SC-009'],
                ['name'=>'Henry A. Kwofie','email'=>'henry.kwofie@jsg.gov.gh','emp_id'=>'SC-010'],
                ['name'=>'Yaw Darko Asare','email'=>'yaw.asare@jsg.gov.gh','emp_id'=>'SC-011'],
                ['name'=>'Richard Adjei-Frimpong','email'=>'richard.adjei-frimpong@jsg.gov.gh','emp_id'=>'SC-012'],
                ['name'=>'Senyo Dzamefe','email'=>'senyo.dzamefe@jsg.gov.gh','emp_id'=>'SC-013'],
                ['name'=>'Dennis Dominic Adjei','email'=>'dennis.adjei@jsg.gov.gh','emp_id'=>'SC-014'],
                ['name'=>'Gbiel Simon Suurbaareh','email'=>'gbiel.suurbaareh@jsg.gov.gh','emp_id'=>'SC-015'],
                ['name'=>'Janapare Adzua Bartels-Kodwo','email'=>'janapare.bartels-kodwo@jsg.gov.gh','emp_id'=>'SC-016'],
                ['name'=>'Hafisata Amaleboba','email'=>'hafisata.amaleboba@jsg.gov.gh','emp_id'=>'SC-017'],
                ['name'=>'Kweku Tawiah Ackaah-Boafo','email'=>'kweku.ackaah-boafo@jsg.gov.gh','emp_id'=>'SC-018'],
                ],
            ],
            [
                'level'  => 'Court of Appeal',
                'judges' => [
                ['name'=>'Mabel Maame Agyemang','email'=>'mabel.agyemang@jsg.gov.gh','emp_id'=>'CA-001'],
                ['name'=>'Anthony Oppong','email'=>'anthony.oppong@jsg.gov.gh','emp_id'=>'CA-002'],
                ['name'=>'Angelina Mensah-Homiah','email'=>'angelina.mensah-homiah@jsg.gov.gh','emp_id'=>'CA-003'],
                ['name'=>'Jennifer A. Dodoo','email'=>'jennifer.dodoo@jsg.gov.gh','emp_id'=>'CA-004'],
                ['name'=>'Sophia Rosetta Bernasko Essah','email'=>'sophia.essah@jsg.gov.gh','emp_id'=>'CA-005'],
                ['name'=>'Georgina Mensah-Datsa','email'=>'georgina.mensah-datsa@jsg.gov.gh','emp_id'=>'CA-006'],
                ['name'=>'Eric Kyei Baffour','email'=>'eric.kyei-baffour@jsg.gov.gh','emp_id'=>'CA-007'],
                ['name'=>'Edward Amoako Asante','email'=>'edward.asante@jsg.gov.gh','emp_id'=>'CA-008'],
                ['name'=>'Eric Baah','email'=>'eric.baah@jsg.gov.gh','emp_id'=>'CA-009'],
                ['name'=>'Cyra Pamela Cynthia A. Koranteng','email'=>'cyra.koranteng@jsg.gov.gh','emp_id'=>'CA-010'],
                ['name'=>'Alex Owusu-Ofori','email'=>'alex.owusu-ofori@jsg.gov.gh','emp_id'=>'CA-011'],
                ['name'=>'Emmanuel Ankamah','email'=>'emmanuel.ankamah@jsg.gov.gh','emp_id'=>'CA-012'],
                ['name'=>'Jerome Noble-Nkrumah','email'=>'jerome.noble-nkrumah@jsg.gov.gh','emp_id'=>'CA-013'],
                ['name'=>'Gifty Agyei Addo','email'=>'gifty.addo@jsg.gov.gh','emp_id'=>'CA-014'],
                ['name'=>'Afia Serwah Asare-Botwe','email'=>'afia.asare-botwe@jsg.gov.gh','emp_id'=>'CA-015'],
                ['name'=>'Samuel Obeng-Diawuo','email'=>'samuel.obeng-diawuo@jsg.gov.gh','emp_id'=>'CA-016'],
                ['name'=>'Jennifer Abena Dadzie','email'=>'jennifer.dadzie@jsg.gov.gh','emp_id'=>'CA-017'],
                ['name'=>'Charles Edward Ekow Baiden','email'=>'charles.baiden@jsg.gov.gh','emp_id'=>'CA-018'],
                ['name'=>'Stephen Oppong','email'=>'stephen.oppong@jsg.gov.gh','emp_id'=>'CA-019'],
                ['name'=>'Patrick Kwamina Baiden','email'=>'patrick.baiden@jsg.gov.gh','emp_id'=>'CA-020'],
                ['name'=>'Olivia Anku-Tsede','email'=>'olivia.anku-tsede@jsg.gov.gh','emp_id'=>'CA-021'],
                ['name'=>'Christopher Archer','email'=>'christopher.archer@jsg.gov.gh','emp_id'=>'CA-022'],
                ['name'=>'Ernest Owusu-Dapaah','email'=>'ernest.owusu-dapaah@jsg.gov.gh','emp_id'=>'CA-023'],
                ['name'=>'Charles Gyamfi Danquah','email'=>'charles.danquah@jsg.gov.gh','emp_id'=>'CA-024'],
                ['name'=>'Gifty Dekyem','email'=>'gifty.dekyem@jsg.gov.gh','emp_id'=>'CA-025'],
                ['name'=>'Kofi Akrowiah','email'=>'kofi.akrowiah@jsg.gov.gh','emp_id'=>'CA-026'],
                ['name'=>'Richard Mac Kogyapwah','email'=>'richard.kogyapwah@jsg.gov.gh','emp_id'=>'CA-027'],
                ['name'=>'Kwasi Boakye','email'=>'kwasi.boakye@jsg.gov.gh','emp_id'=>'CA-028'],
                ['name'=>'Alexander Osei Tutu','email'=>'alexander.tutu@jsg.gov.gh','emp_id'=>'CA-029'],
                ['name'=>'Francis Obiri','email'=>'francis.obiri@jsg.gov.gh','emp_id'=>'CA-030'],
                ['name'=>'Lydia Osei Marfo','email'=>'lydia.marfo@jsg.gov.gh','emp_id'=>'CA-031'],
                ['name'=>'Aboagye Tandoh','email'=>'aboagye.tandoh@jsg.gov.gh','emp_id'=>'CA-032'],
                ['name'=>'Mariam Agyeman Gyasi Jawhary','email'=>'mariam.jawhary@jsg.gov.gh','emp_id'=>'CA-033'],
                ['name'=>'Yaa Onyameye Gyakobo','email'=>'yaa.gyakobo@jsg.gov.gh','emp_id'=>'CA-034'],
                ['name'=>'Francis Koffie','email'=>'francis.koffie@jsg.gov.gh','emp_id'=>'CA-035'],
                ['name'=>'Charles William Leopold Bartels Zwennes','email'=>'charles.zwennes@jsg.gov.gh','emp_id'=>'CA-036'],
                ['name'=>'Yaw Kodie Oppong','email'=>'yaw.oppong@jsg.gov.gh','emp_id'=>'CA-037'],
                ['name'=>'David Kwabena Adade Boafo','email'=>'david.boafo@jsg.gov.gh','emp_id'=>'CA-038'],
                ['name'=>'Poku Adusei','email'=>'poku.adusei@jsg.gov.gh','emp_id'=>'CA-039'],
                ['name'=>'Cecilia Naa Shormeh Davis','email'=>'cecilia.davis@jsg.gov.gh','emp_id'=>'CA-040'],
                ['name'=>'Justin Kofi Dorgu','email'=>'justin.dorgu@jsg.gov.gh','emp_id'=>'CA-041'],
                ['name'=>'Daniel Mensah','email'=>'daniel.mensah@jsg.gov.gh','emp_id'=>'CA-042'],
                ['name'=>'George Buadi','email'=>'george.buadi@jsg.gov.gh','emp_id'=>'CA-043'],
                ['name'=>'Olivia Obeng Owusu','email'=>'olivia.owusu@jsg.gov.gh','emp_id'=>'CA-044'],
                ['name'=>'John Bosco Nabarese','email'=>'john.nabarese@jsg.gov.gh','emp_id'=>'CA-045'],
                ['name'=>'Jennifer Anne Myers Ahmed','email'=>'jennifer.ahmed@jsg.gov.gh','emp_id'=>'CA-046'],
                ['name'=>'Emmanuel Senyo Amedahe','email'=>'emmanuel.amedahe@jsg.gov.gh','emp_id'=>'CA-047'],
                ['name'=>'Kwasi Anokye Gyimah','email'=>'kwasi.gyimah@jsg.gov.gh','emp_id'=>'CA-048'],
                ['name'=>'Richmond Osei Hwere','email'=>'richmond.hwere@jsg.gov.gh','emp_id'=>'CA-049'],
                ['name'=>'Francis Apongabuno Achibonga','email'=>'francis.achibonga@jsg.gov.gh','emp_id'=>'CA-050'],
                ['name'=>'Ali Baba Abature','email'=>'ali.abature@jsg.gov.gh','emp_id'=>'CA-051'],
                ['name'=>'Abena Asuamah Oppong','email'=>'abena.oppong@jsg.gov.gh','emp_id'=>'CA-052'],
                ['name'=>'Mariama Sammo','email'=>'mariama.sammo@jsg.gov.gh','emp_id'=>'CA-053'],
                ['name'=>'Mary Maame Ekue Yanzuh','email'=>'mary.yanzuh@jsg.gov.gh','emp_id'=>'CA-054'],
                ['name'=>'Ayitey Armah-Tetteh','email'=>'ayitey.armah-tetteh@jsg.gov.gh','emp_id'=>'CA-055'],
                ['name'=>'Charity Akosua Asem','email'=>'charity.asem@jsg.gov.gh','emp_id'=>'CA-056'],
                ['name'=>'Enyonam Adinyira','email'=>'enyonam.adinyira@jsg.gov.gh','emp_id'=>'CA-057'],
                ['name'=>'Sheila Minta','email'=>'sheila.minta@jsg.gov.gh','emp_id'=>'CA-058'],
                ['name'=>'Douglas Seidu','email'=>'douglas.seidu@jsg.gov.gh','emp_id'=>'CA-059'],
                ['name'=>'Charles Adjei Wilson','email'=>'charles.wilson@jsg.gov.gh','emp_id'=>'CA-060'],
                ['name'=>'Franklina Gesila Adanu','email'=>'franklina.adanu@jsg.gov.gh','emp_id'=>'CA-061'],
                ],
            ],
            [
                'level'  => 'High Court',
                'judges' => [
                ['name'=>'Ananda Juliana Aikins','email'=>'ananda.aikins@jsg.gov.gh','emp_id'=>'HC-001'],
                ['name'=>'George Krofa Addae','email'=>'george.addae@jsg.gov.gh','emp_id'=>'HC-002'],
                ['name'=>'Emmanuel Amo Yartey','email'=>'emmanuel.yartey@jsg.gov.gh','emp_id'=>'HC-003'],
                ['name'=>'Barbara N. Tetteh-Charway','email'=>'barbara.tetteh-charway@jsg.gov.gh','emp_id'=>'HC-004'],
                ['name'=>'Doreen Genevieve Boakye-Agyei','email'=>'doreen.boakye-agyei@jsg.gov.gh','emp_id'=>'HC-005'],
                ['name'=>'Hannah Taylor','email'=>'hannah.taylor@jsg.gov.gh','emp_id'=>'HC-006'],
                ['name'=>'William Boampong','email'=>'william.boampong@jsg.gov.gh','emp_id'=>'HC-007'],
                ['name'=>'Kwame Gyamfi Osei','email'=>'kwame.osei@jsg.gov.gh','emp_id'=>'HC-008'],
                ['name'=>'Juliana E. Amonoo-Neizer','email'=>'juliana.amonoo-neizer@jsg.gov.gh','emp_id'=>'HC-009'],
                ['name'=>'Akua Sarpomaa Amoah','email'=>'akua.amoah@jsg.gov.gh','emp_id'=>'HC-010'],
                ['name'=>'Kofi Nyanteh Akuffo','email'=>'kofi.akuffo@jsg.gov.gh','emp_id'=>'HC-011'],
                ['name'=>'Samuel Asare-Nyako','email'=>'samuel.asare-nyako@jsg.gov.gh','emp_id'=>'HC-012'],
                ['name'=>'Emmanuel Lodoh','email'=>'emmanuel.lodoh@jsg.gov.gh','emp_id'=>'HC-013'],
                ['name'=>'Sedina Agbemava','email'=>'sedina.agbemava@jsg.gov.gh','emp_id'=>'HC-014'],
                ['name'=>'Ellen Vivian Amoah','email'=>'ellen.amoah@jsg.gov.gh','emp_id'=>'HC-015'],
                ['name'=>'John Ekow Mensah','email'=>'john.mensah@jsg.gov.gh','emp_id'=>'HC-016'],
                ['name'=>'Janet Anima Maafo','email'=>'janet.maafo@jsg.gov.gh','emp_id'=>'HC-017'],
                ['name'=>'Afia Nyako Adu-Amankwa','email'=>'afia.adu-amankwa@jsg.gov.gh','emp_id'=>'HC-018'],
                ['name'=>'Frederick Tetteh','email'=>'frederick.tetteh@jsg.gov.gh','emp_id'=>'HC-019'],
                ['name'=>'Joan Eyi King','email'=>'joan.king@jsg.gov.gh','emp_id'=>'HC-020'],
                ['name'=>'John Eugene Nyante Nyadu','email'=>'john.nyadu@jsg.gov.gh','emp_id'=>'HC-021'],
                ['name'=>'Gabriel Nene Kwao Mate-Teye','email'=>'gabriel.mate-teye@jsg.gov.gh','emp_id'=>'HC-022'],
                ['name'=>'Afi Agbanu Kudomor','email'=>'afi.kudomor@jsg.gov.gh','emp_id'=>'HC-023'],
                ['name'=>'Patricia Quansah','email'=>'patricia.quansah@jsg.gov.gh','emp_id'=>'HC-024'],
                ['name'=>'Ruby Aryeetey','email'=>'ruby.aryeetey@jsg.gov.gh','emp_id'=>'HC-025'],
                ['name'=>'Kwame Amoako','email'=>'kwame.amoako@jsg.gov.gh','emp_id'=>'HC-026'],
                ['name'=>'Mariam Saleh Sinare','email'=>'mariam.sinare@jsg.gov.gh','emp_id'=>'HC-027'],
                ['name'=>'Cynthia Wiredu','email'=>'cynthia.wiredu@jsg.gov.gh','emp_id'=>'HC-028'],
                ['name'=>'Frank Aboadwe Rockson','email'=>'frank.rockson@jsg.gov.gh','emp_id'=>'HC-029'],
                ['name'=>'Emmanuel Ayensu Essampong','email'=>'emmanuel.essampong@jsg.gov.gh','emp_id'=>'HC-030'],
                ['name'=>'Fredrick Arnord Wekem Kwesi Nawurah','email'=>'fredrick.nawurah@jsg.gov.gh','emp_id'=>'HC-031'],
                ['name'=>'Rita Abena Abrokwah Doku','email'=>'rita.doku@jsg.gov.gh','emp_id'=>'HC-032'],
                ['name'=>'Comfort Kwasiwor Tasiame','email'=>'comfort.tasiame@jsg.gov.gh','emp_id'=>'HC-033'],
                ['name'=>'Ruby Naa Adjeley Quaison','email'=>'ruby.quaison@jsg.gov.gh','emp_id'=>'HC-034'],
                ['name'=>'Priscilla Dirkro','email'=>'priscilla.dirkro@jsg.gov.gh','emp_id'=>'HC-035'],
                ['name'=>'Jane Harriet Akweley Quaye','email'=>'jane.quaye@jsg.gov.gh','emp_id'=>'HC-036'],
                ['name'=>'Malike Awo Woanyah','email'=>'malike.woanyah@jsg.gov.gh','emp_id'=>'HC-037'],
                ['name'=>'Doris Dabanka-Bekoe','email'=>'doris.dabanka-bekoe@jsg.gov.gh','emp_id'=>'HC-038'],
                ['name'=>'Emmanuel Kofi Diaba','email'=>'emmanuel.diaba@jsg.gov.gh','emp_id'=>'HC-039'],
                ['name'=>'Sarah Aryee','email'=>'sarah.aryee@jsg.gov.gh','emp_id'=>'HC-040'],
                ['name'=>'Mavis Akua Andoh','email'=>'mavis.andoh@jsg.gov.gh','emp_id'=>'HC-041'],
                ['name'=>'Eudora Christina Dadson','email'=>'eudora.dadson@jsg.gov.gh','emp_id'=>'HC-042'],
                ['name'=>'George Appah Kwabeng','email'=>'george.kwabeng@jsg.gov.gh','emp_id'=>'HC-043'],
                ['name'=>'Amos Wuntah Wuni','email'=>'amos.wuni@jsg.gov.gh','emp_id'=>'HC-044'],
                ['name'=>'Audrey Kocuvie-Tay','email'=>'audrey.kocuvie-tay@jsg.gov.gh','emp_id'=>'HC-045'],
                ['name'=>'Eva Ofori-Darko','email'=>'eva.ofori-darko@jsg.gov.gh','emp_id'=>'HC-046'],
                ['name'=>'Emmanuel Bart-Plange Brew','email'=>'emmanuel.brew@jsg.gov.gh','emp_id'=>'HC-047'],
                ['name'=>'Yaw Owoahene-Acheampong','email'=>'yaw.owoahene-acheampong@jsg.gov.gh','emp_id'=>'HC-048'],
                ['name'=>'Samuel Boakye-Yiadom','email'=>'samuel.boakye-yiadom@jsg.gov.gh','emp_id'=>'HC-049'],
                ['name'=>'Abdul Yusif Asibey','email'=>'abdul.asibey@jsg.gov.gh','emp_id'=>'HC-050'],
                ['name'=>'Elfreda Amy Dankyi','email'=>'elfreda.dankyi@jsg.gov.gh','emp_id'=>'HC-051'],
                ['name'=>'Samuel Faraday Johnson','email'=>'samuel.johnson@jsg.gov.gh','emp_id'=>'HC-052'],
                ['name'=>'Nana Yaw Gyamfi Frimpong','email'=>'nana.frimpong@jsg.gov.gh','emp_id'=>'HC-053'],
                ['name'=>'Solomon Oppong-Twumasi','email'=>'solomon.oppong-twumasi@jsg.gov.gh','emp_id'=>'HC-054'],
                ['name'=>'Charles Bentum','email'=>'charles.bentum@jsg.gov.gh','emp_id'=>'HC-055'],
                ['name'=>'Joseph Adu-Owusu Agyeman','email'=>'joseph.agyeman@jsg.gov.gh','emp_id'=>'HC-056'],
                ['name'=>'William Osei Kuffour','email'=>'william.kuffour@jsg.gov.gh','emp_id'=>'HC-057'],
                ['name'=>'Ebenezer Osei Darko','email'=>'ebenezer.darko@jsg.gov.gh','emp_id'=>'HC-058'],
                ['name'=>'Bernard Bentil','email'=>'bernard.bentil@jsg.gov.gh','emp_id'=>'HC-059'],
                ['name'=>'Alexander Graham','email'=>'alexander.graham@jsg.gov.gh','emp_id'=>'HC-060'],
                ['name'=>'Mercy Adei Kotei','email'=>'mercy.kotei@jsg.gov.gh','emp_id'=>'HC-061'],
                ['name'=>'George Kwame Gyan-Kontoh','email'=>'george.gyan-kontoh@jsg.gov.gh','emp_id'=>'HC-062'],
                ['name'=>'Richard Apietu','email'=>'richard.apietu@jsg.gov.gh','emp_id'=>'HC-063'],
                ['name'=>'Eric Ansah Ankomah','email'=>'eric.ankomah@jsg.gov.gh','emp_id'=>'HC-064'],
                ['name'=>'Cynthia Martinson','email'=>'cynthia.martinson@jsg.gov.gh','emp_id'=>'HC-065'],
                ['name'=>'Bridget Kafui Antonio-Apedzi','email'=>'bridget.antonio-apedzi@jsg.gov.gh','emp_id'=>'HC-066'],
                ['name'=>'Nabeela Naeema Wahab','email'=>'nabeela.wahab@jsg.gov.gh','emp_id'=>'HC-067'],
                ['name'=>'Kwame Polley','email'=>'kwame.polley@jsg.gov.gh','emp_id'=>'HC-068'],
                ['name'=>'William Appiah Twumasi','email'=>'william.twumasi@jsg.gov.gh','emp_id'=>'HC-069'],
                ['name'=>'Baah Forson Agyapong','email'=>'baah.agyapong@jsg.gov.gh','emp_id'=>'HC-070'],
                ['name'=>'Marian Affoh','email'=>'marian.affoh@jsg.gov.gh','emp_id'=>'HC-071'],
                ['name'=>'Nana Brew','email'=>'nana.brew@jsg.gov.gh','emp_id'=>'HC-072'],
                ['name'=>'Abena Amponsah Buansi','email'=>'abena.buansi@jsg.gov.gh','emp_id'=>'HC-073'],
                ['name'=>'Ellen Lordina Serwaa Mireku','email'=>'ellen.mireku@jsg.gov.gh','emp_id'=>'HC-074'],
                ['name'=>'Priscilla Dapaah Mireku','email'=>'priscilla.mireku@jsg.gov.gh','emp_id'=>'HC-075'],
                ['name'=>'Alexander Oworae','email'=>'alexander.oworae@jsg.gov.gh','emp_id'=>'HC-076'],
                ['name'=>'Joyce Boahen','email'=>'joyce.boahen@jsg.gov.gh','emp_id'=>'HC-077'],
                ['name'=>'Edward Twum','email'=>'edward.twum@jsg.gov.gh','emp_id'=>'HC-078'],
                ['name'=>'Gwendolyn Millicent Owusu','email'=>'gwendolyn.owusu@jsg.gov.gh','emp_id'=>'HC-079'],
                ['name'=>'Rosemary Baah Tosu','email'=>'rosemary.tosu@jsg.gov.gh','emp_id'=>'HC-080'],
                ['name'=>'Frederick Kwabena Twumasi','email'=>'frederick.twumasi@jsg.gov.gh','emp_id'=>'HC-081'],
                ['name'=>'Adelaide Abui Keddey','email'=>'adelaide.keddey@jsg.gov.gh','emp_id'=>'HC-082'],
                ['name'=>'Kenneth Edem Kudjordjie','email'=>'kenneth.kudjordjie@jsg.gov.gh','emp_id'=>'HC-083'],
                ['name'=>'Harry Acheampong-Opoku','email'=>'harry.acheampong-opoku@jsg.gov.gh','emp_id'=>'HC-084'],
                ['name'=>'John-Mark Nuku Alifo','email'=>'john-mark.alifo@jsg.gov.gh','emp_id'=>'HC-085'],
                ['name'=>'Kwesi Adjenim-Boateng','email'=>'kwesi.adjenim-boateng@jsg.gov.gh','emp_id'=>'HC-086'],
                ['name'=>'George Aikins Ampiah-Bonney','email'=>'george.ampiah-bonney@jsg.gov.gh','emp_id'=>'HC-087'],
                ['name'=>'Marie-Louise Simmons','email'=>'marie-louise.simmons@jsg.gov.gh','emp_id'=>'HC-088'],
                ['name'=>'Dorothy Ayodele Kingsley Nyinah','email'=>'dorothy.nyinah@jsg.gov.gh','emp_id'=>'HC-089'],
                ['name'=>'Ama Sefenya Ayittey','email'=>'ama.ayittey@jsg.gov.gh','emp_id'=>'HC-090'],
                ['name'=>'Abigail Animah Asare','email'=>'abigail.asare@jsg.gov.gh','emp_id'=>'HC-091'],
                ['name'=>'Dorinda Smith Arthur','email'=>'dorinda.arthur@jsg.gov.gh','emp_id'=>'HC-092'],
                ['name'=>'Veronique Praba Tetteh','email'=>'veronique.tetteh@jsg.gov.gh','emp_id'=>'HC-093'],
                ['name'=>'Charles Kwasi Acheampong','email'=>'charles.acheampong@jsg.gov.gh','emp_id'=>'HC-094'],
                ['name'=>'Arit Nsemoh','email'=>'arit.nsemoh@jsg.gov.gh','emp_id'=>'HC-095'],
                ['name'=>'Abdul Razak Musah','email'=>'abdul.musah@jsg.gov.gh','emp_id'=>'HC-096'],
                ['name'=>'Samuel Djanie Kotey','email'=>'samuel.kotey@jsg.gov.gh','emp_id'=>'HC-097'],
                ['name'=>'Stephen Kumi','email'=>'stephen.kumi@jsg.gov.gh','emp_id'=>'HC-098'],
                ['name'=>'Abass Abubakari Adams','email'=>'abass.adams@jsg.gov.gh','emp_id'=>'HC-099'],
                ['name'=>'Felix Datsomor','email'=>'felix.datsomor@jsg.gov.gh','emp_id'=>'HC-100'],
                ['name'=>'Agnes Opoku-Barnieh','email'=>'agnes.opoku-barnieh@jsg.gov.gh','emp_id'=>'HC-101'],
                ['name'=>'Afia Owusuaa Appiah','email'=>'afia.appiah@jsg.gov.gh','emp_id'=>'HC-102'],
                ['name'=>'Ellen Ofei-Ayeh','email'=>'ellen.ofei-ayeh@jsg.gov.gh','emp_id'=>'HC-103'],
                ['name'=>'Winnie Amoatey-Owusu','email'=>'winnie.amoatey-owusu@jsg.gov.gh','emp_id'=>'HC-104'],
                ['name'=>'Enid Marful Sau','email'=>'enid.sau@jsg.gov.gh','emp_id'=>'HC-105'],
                ['name'=>'Kizita Naa Koowa Quarshie','email'=>'kizita.quarshie@jsg.gov.gh','emp_id'=>'HC-106'],
                ['name'=>'Ernest Pascal Gemadzie','email'=>'ernest.gemadzie@jsg.gov.gh','emp_id'=>'HC-107'],
                ['name'=>'Nathan Parker Yarney','email'=>'nathan.yarney@jsg.gov.gh','emp_id'=>'HC-108'],
                ['name'=>'Oliver Abada','email'=>'oliver.abada@jsg.gov.gh','emp_id'=>'HC-109'],
                ['name'=>'Frimpong Amoako','email'=>'frimpong.amoako@jsg.gov.gh','emp_id'=>'HC-110'],
                ['name'=>'Akosua Dansoa Asiama Christopher','email'=>'akosua.christopher@jsg.gov.gh','emp_id'=>'HC-111'],
                ['name'=>'Frank Asong Obuajo','email'=>'frank.obuajo@jsg.gov.gh','emp_id'=>'HC-112'],
                ['name'=>'Moses Bedima Duut','email'=>'moses.duut@jsg.gov.gh','emp_id'=>'HC-113'],
                ['name'=>'Nathaniel Hegbor','email'=>'nathaniel.hegbor@jsg.gov.gh','emp_id'=>'HC-114'],
                ['name'=>'Cyracus Badinye Bapuuroh','email'=>'cyracus.bapuuroh@jsg.gov.gh','emp_id'=>'HC-115'],
                ['name'=>'Vivian Mfodwaa Gyan','email'=>'vivian.gyan@jsg.gov.gh','emp_id'=>'HC-116'],
                ['name'=>'Osei-Wusu Antwi','email'=>'osei-wusu.antwi@jsg.gov.gh','emp_id'=>'HC-117'],
                ['name'=>'Akpene Dzigbordi Motey','email'=>'akpene.motey@jsg.gov.gh','emp_id'=>'HC-118'],
                ['name'=>'Charles Edward Yirenkyi Addo','email'=>'charles.addo@jsg.gov.gh','emp_id'=>'HC-119'],
                ['name'=>'Rosemarie Afua Asante','email'=>'rosemarie.asante@jsg.gov.gh','emp_id'=>'HC-120'],
                ['name'=>'Diana Adu-Anane','email'=>'diana.adu-anane@jsg.gov.gh','emp_id'=>'HC-121'],
                ['name'=>'Mark Tarima Diboro','email'=>'mark.diboro@jsg.gov.gh','emp_id'=>'HC-122'],
                ['name'=>'Ama Hathia Manu','email'=>'ama.manu@jsg.gov.gh','emp_id'=>'HC-123'],
                ['name'=>'Mawusi Bedjrah','email'=>'mawusi.bedjrah@jsg.gov.gh','emp_id'=>'HC-124'],
                ['name'=>'Jacqueline Awusi-Sekyi Avotri','email'=>'jacqueline.avotri@jsg.gov.gh','emp_id'=>'HC-125'],
                ['name'=>'Malcolm Ewoenam Bedzrah','email'=>'malcolm.bedzrah@jsg.gov.gh','emp_id'=>'HC-126'],
                ['name'=>'Yaw Poku Achampong','email'=>'yaw.achampong@jsg.gov.gh','emp_id'=>'HC-127'],
                ['name'=>'Sylvester Nii Okine Ablorh','email'=>'sylvester.ablorh@jsg.gov.gh','emp_id'=>'HC-128'],
                ['name'=>'Franklin Titus-Glover','email'=>'franklin.titus-glover@jsg.gov.gh','emp_id'=>'HC-129'],
                ['name'=>'Christina Cann','email'=>'christina.cann@jsg.gov.gh','emp_id'=>'HC-130'],
                ['name'=>'Isaac Addo','email'=>'isaac.addo@jsg.gov.gh','emp_id'=>'HC-131'],
                ['name'=>'Peter Oppong Boahen','email'=>'peter.boahen@jsg.gov.gh','emp_id'=>'HC-132'],
                ['name'=>'Jonathan Desmond Nunoo','email'=>'jonathan.nunoo@jsg.gov.gh','emp_id'=>'HC-133'],
                ['name'=>'Dora Gloria Araba Eshun','email'=>'dora.eshun@jsg.gov.gh','emp_id'=>'HC-134'],
                ['name'=>'Naa Amerley Akowuah','email'=>'naa.akowuah@jsg.gov.gh','emp_id'=>'HC-135'],
                ['name'=>'Ebenezer Kweku Ansah','email'=>'ebenezer.ansah@jsg.gov.gh','emp_id'=>'HC-136'],
                ['name'=>'Jonathan Avogo','email'=>'jonathan.avogo@jsg.gov.gh','emp_id'=>'HC-137'],
                ['name'=>'Joshua Caleb Abaidoo','email'=>'joshua.abaidoo@jsg.gov.gh','emp_id'=>'HC-138'],
                ['name'=>'Gloria Naa Botor Laryea','email'=>'gloria.laryea@jsg.gov.gh','emp_id'=>'HC-139'],
                ['name'=>'Gloria Mensah-Bonsu','email'=>'gloria.mensah-bonsu@jsg.gov.gh','emp_id'=>'HC-140'],
                ['name'=>'Samuel Bright Acquah','email'=>'samuel.acquah@jsg.gov.gh','emp_id'=>'HC-141'],
                ['name'=>'Halimah El-Alawah Abdul-Baasit','email'=>'halimah.abdul-baasit@jsg.gov.gh','emp_id'=>'HC-142'],
                ['name'=>'Bertha Aniagyei','email'=>'bertha.aniagyei@jsg.gov.gh','emp_id'=>'HC-143'],
                ['name'=>'Sedinam Awo Balokah','email'=>'sedinam.balokah@jsg.gov.gh','emp_id'=>'HC-144'],
                ['name'=>'Eleanor Kakra Barnes-Botchway','email'=>'eleanor.barnes-botchway@jsg.gov.gh','emp_id'=>'HC-145'],
                ['name'=>'Osman Abdul-Hakeem','email'=>'osman.abdul-hakeem@jsg.gov.gh','emp_id'=>'HC-146'],
                ['name'=>'Paul Oduro','email'=>'paul.oduro@jsg.gov.gh','emp_id'=>'HC-147'],
                ['name'=>'Klorkor Okai-Mills','email'=>'klorkor.okai-mills@jsg.gov.gh','emp_id'=>'HC-148'],
                ],
            ],
            [
                'level'  => 'Circuit Court Judge',
                'judges' => [
                ['name'=>'Michael Johnson Abbey','email'=>'michael.abbey@jsg.gov.gh','emp_id'=>'CC-001'],
                ['name'=>'Kofi Amoako Osei','email'=>'kofi.osei@jsg.gov.gh','emp_id'=>'CC-002'],
                ['name'=>'Frank Yao Gbeddy','email'=>'frank.gbeddy@jsg.gov.gh','emp_id'=>'CC-003'],
                ['name'=>'Susana Eduful','email'=>'susana.eduful@jsg.gov.gh','emp_id'=>'CC-004'],
                ['name'=>'Evelyn Asamoah','email'=>'evelyn.asamoah@jsg.gov.gh','emp_id'=>'CC-005'],
                ['name'=>'Joseph Ofosu Behome','email'=>'joseph.behome@jsg.gov.gh','emp_id'=>'CC-006'],
                ['name'=>'Kwabena Kodua Obiri-Yeboah','email'=>'kwabena.obiri-yeboah@jsg.gov.gh','emp_id'=>'CC-007'],
                ['name'=>'Nana Asantewaa Attakorah','email'=>'nana.attakorah@jsg.gov.gh','emp_id'=>'CC-008'],
                ['name'=>'Festus Fovi Nukunu','email'=>'festus.nukunu@jsg.gov.gh','emp_id'=>'CC-009'],
                ['name'=>'Appiatse Kwasi Abaidoo','email'=>'appiatse.abaidoo@jsg.gov.gh','emp_id'=>'CC-010'],
                ['name'=>'Fred Obikyere','email'=>'fred.obikyere@jsg.gov.gh','emp_id'=>'CC-011'],
                ['name'=>'Nana Asibey Osei','email'=>'nana.osei@jsg.gov.gh','emp_id'=>'CC-012'],
                ['name'=>'Isaac Apeatu','email'=>'isaac.apeatu@jsg.gov.gh','emp_id'=>'CC-013'],
                ['name'=>'Joseph Nadaado Mcali Jnr','email'=>'joseph.jnr@jsg.gov.gh','emp_id'=>'CC-014'],
                ['name'=>'Jojo Amoah Hagan','email'=>'jojo.hagan@jsg.gov.gh','emp_id'=>'CC-015'],
                ['name'=>'Rosemond Dodua Agyiri','email'=>'rosemond.agyiri@jsg.gov.gh','emp_id'=>'CC-016'],
                ['name'=>'Robert Addo','email'=>'robert.addo@jsg.gov.gh','emp_id'=>'CC-017'],
                ['name'=>'James Kojoh Botah','email'=>'james.botah@jsg.gov.gh','emp_id'=>'CC-018'],
                ['name'=>'Isaac Oheneba-Kuffour','email'=>'isaac.oheneba-kuffour@jsg.gov.gh','emp_id'=>'CC-019'],
                ['name'=>'Maame Efua Tordimah','email'=>'maame.tordimah@jsg.gov.gh','emp_id'=>'CC-020'],
                ['name'=>'Akosua Anokyewaa Adjepong','email'=>'akosua.adjepong@jsg.gov.gh','emp_id'=>'CC-021'],
                ['name'=>'Angela Attachie','email'=>'angela.attachie@jsg.gov.gh','emp_id'=>'CC-022'],
                ['name'=>'Simon Nketiah Gaga','email'=>'simon.gaga@jsg.gov.gh','emp_id'=>'CC-023'],
                ['name'=>'Lily Amoah Kankam','email'=>'lily.kankam@jsg.gov.gh','emp_id'=>'CC-024'],
                ['name'=>'Matilda Ribeiro','email'=>'matilda.ribeiro@jsg.gov.gh','emp_id'=>'CC-025'],
                ['name'=>'Sumaila Mbache Ahmadu','email'=>'sumaila.ahmadu@jsg.gov.gh','emp_id'=>'CC-026'],
                ['name'=>'Henrietta Charway','email'=>'henrietta.charway@jsg.gov.gh','emp_id'=>'CC-027'],
                ['name'=>'Adwoa Akyaama Ofosu','email'=>'adwoa.ofosu@jsg.gov.gh','emp_id'=>'CC-028'],
                ['name'=>'Saeed Aliata','email'=>'saeed.aliata@jsg.gov.gh','emp_id'=>'CC-029'],
                ['name'=>'Kwaku Baah Frempong','email'=>'kwaku.frempong@jsg.gov.gh','emp_id'=>'CC-030'],
                ['name'=>'Priscilla Sophia Yeboah','email'=>'priscilla.yeboah@jsg.gov.gh','emp_id'=>'CC-031'],
                ['name'=>'Rosemary Edith Hayford','email'=>'rosemary.hayford@jsg.gov.gh','emp_id'=>'CC-032'],
                ['name'=>'Akua Adu Boahene','email'=>'akua.boahene@jsg.gov.gh','emp_id'=>'CC-033'],
                ['name'=>'Bianca Adwoa Osei-Sarfo','email'=>'bianca.osei-sarfo@jsg.gov.gh','emp_id'=>'CC-034'],
                ['name'=>'Sarah Nyarkoa Nkansah','email'=>'sarah.nkansah@jsg.gov.gh','emp_id'=>'CC-035'],
                ['name'=>'Araba Nunoo','email'=>'araba.nunoo@jsg.gov.gh','emp_id'=>'CC-036'],
                ['name'=>'Nana Adwoa Serwaa Dua-Adonteng','email'=>'nana.dua-adonteng@jsg.gov.gh','emp_id'=>'CC-037'],
                ['name'=>'Akosua Attaa Nyarko','email'=>'akosua.nyarko@jsg.gov.gh','emp_id'=>'CC-038'],
                ['name'=>'Nana Aba Quaiba Nunoo','email'=>'nana.nunoo@jsg.gov.gh','emp_id'=>'CC-039'],
                ['name'=>'Akosua Asantewaa Sarpong','email'=>'akosua.sarpong@jsg.gov.gh','emp_id'=>'CC-040'],
                ['name'=>'Francis Ayamwuni Asobayire','email'=>'francis.asobayire@jsg.gov.gh','emp_id'=>'CC-041'],
                ['name'=>'Frank Asiedu Nimarkoh','email'=>'frank.nimarkoh@jsg.gov.gh','emp_id'=>'CC-042'],
                ['name'=>'Vida Achiaa Yeboah','email'=>'vida.yeboah@jsg.gov.gh','emp_id'=>'CC-043'],
                ['name'=>'Akua Adoma Addae','email'=>'akua.addae@jsg.gov.gh','emp_id'=>'CC-044'],
                ['name'=>'Philomina Ansaah Asiedu','email'=>'philomina.asiedu@jsg.gov.gh','emp_id'=>'CC-045'],
                ['name'=>'Lawrencia Awura Abena Darkowaa Gyamfi','email'=>'lawrencia.gyamfi@jsg.gov.gh','emp_id'=>'CC-046'],
                ['name'=>'Yvonne Gbenakuor Wussah','email'=>'yvonne.wussah@jsg.gov.gh','emp_id'=>'CC-047'],
                ['name'=>'Basilia Adjei-Tawiah','email'=>'basilia.adjei-tawiah@jsg.gov.gh','emp_id'=>'CC-048'],
                ['name'=>'Jonathan Odartey','email'=>'jonathan.odartey@jsg.gov.gh','emp_id'=>'CC-049'],
                ['name'=>'Livingstone Lartey Yaw Ameevor','email'=>'livingstone.ameevor@jsg.gov.gh','emp_id'=>'CC-050'],
                ['name'=>'Jephthah Appau','email'=>'jephthah.appau@jsg.gov.gh','emp_id'=>'CC-051'],
                ['name'=>'Lambert Yinigabague Keriba','email'=>'lambert.keriba@jsg.gov.gh','emp_id'=>'CC-052'],
                ],
            ],
            [
                'level'  => 'Professional Magistrate',
                'judges' => [
                ['name'=>'Isaac Agyei','email'=>'isaac.agyei@jsg.gov.gh','emp_id'=>'PM-001'],
                ['name'=>'Kofi Owusu Sekyere','email'=>'kofi.sekyere@jsg.gov.gh','emp_id'=>'PM-002'],
                ['name'=>'Juliet Osei Duedu','email'=>'juliet.duedu@jsg.gov.gh','emp_id'=>'PM-003'],
                ['name'=>'Eric Danning','email'=>'eric.danning@jsg.gov.gh','emp_id'=>'PM-004'],
                ['name'=>'Linda Amissah','email'=>'linda.amissah@jsg.gov.gh','emp_id'=>'PM-005'],
                ['name'=>'Juliana Shormeh Mensah','email'=>'juliana.mensah@jsg.gov.gh','emp_id'=>'PM-006'],
                ['name'=>'Nancy Aku Adade','email'=>'nancy.adade@jsg.gov.gh','emp_id'=>'PM-007'],
                ['name'=>'Ruby Ntiri Opoku','email'=>'ruby.opoku@jsg.gov.gh','emp_id'=>'PM-008'],
                ['name'=>'Natacha Abena Tuffor','email'=>'natacha.tuffor@jsg.gov.gh','emp_id'=>'PM-009'],
                ['name'=>'Stephen Ofori Akrasi','email'=>'stephen.akrasi@jsg.gov.gh','emp_id'=>'PM-010'],
                ['name'=>'Hilda Esther Wryter','email'=>'hilda.wryter@jsg.gov.gh','emp_id'=>'PM-011'],
                ['name'=>'Annette Sophia Essel','email'=>'annette.essel@jsg.gov.gh','emp_id'=>'PM-012'],
                ['name'=>'Bridget Akpe Akattah','email'=>'bridget.akattah@jsg.gov.gh','emp_id'=>'PM-013'],
                ['name'=>'Bernice Mensimah Ackon','email'=>'bernice.ackon@jsg.gov.gh','emp_id'=>'PM-014'],
                ['name'=>'Stanley Adjei','email'=>'stanley.adjei@jsg.gov.gh','emp_id'=>'PM-015'],
                ['name'=>'Awo Amissah French','email'=>'awo.french@jsg.gov.gh','emp_id'=>'PM-016'],
                ['name'=>'Ama Adomako-Kwakye','email'=>'ama.adomako-kwakye@jsg.gov.gh','emp_id'=>'PM-017'],
                ['name'=>'Samuel Boafo Amewuho','email'=>'samuel.amewuho@jsg.gov.gh','emp_id'=>'PM-018'],
                ['name'=>'Afia Densi Asare-Kyire','email'=>'afia.asare-kyire@jsg.gov.gh','emp_id'=>'PM-019'],
                ['name'=>'Catherine Addo Obiri','email'=>'catherine.obiri@jsg.gov.gh','emp_id'=>'PM-020'],
                ['name'=>'Nana Abena Asoh Owusu-Omenyo','email'=>'nana.owusu-omenyo@jsg.gov.gh','emp_id'=>'PM-021'],
                ['name'=>'Naomi Adusei Amaniampong Kuntour','email'=>'naomi.kuntour@jsg.gov.gh','emp_id'=>'PM-022'],
                ['name'=>'Susanna Nyakotey','email'=>'susanna.nyakotey@jsg.gov.gh','emp_id'=>'PM-023'],
                ['name'=>'Linda Enyonam Nyahe','email'=>'linda.nyahe@jsg.gov.gh','emp_id'=>'PM-024'],
                ['name'=>'Isaac Osei Asare','email'=>'isaac.asare@jsg.gov.gh','emp_id'=>'PM-025'],
                ['name'=>'Christiana Odarkor Bruce-Ashirifie','email'=>'christiana.bruce-ashirifie@jsg.gov.gh','emp_id'=>'PM-026'],
                ['name'=>'Cynthia Emefa Ohene','email'=>'cynthia.ohene@jsg.gov.gh','emp_id'=>'PM-027'],
                ['name'=>'Dennis Eyram Fumey','email'=>'dennis.fumey@jsg.gov.gh','emp_id'=>'PM-028'],
                ['name'=>'Maxwell Ofori Kpodo','email'=>'maxwell.kpodo@jsg.gov.gh','emp_id'=>'PM-029'],
                ['name'=>'Victoria Vera Akonu','email'=>'victoria.akonu@jsg.gov.gh','emp_id'=>'PM-030'],
                ['name'=>'William Ofori-Aboagye','email'=>'william.ofori-aboagye@jsg.gov.gh','emp_id'=>'PM-031'],
                ['name'=>'Angela Kesse Mireku','email'=>'angela.mireku@jsg.gov.gh','emp_id'=>'PM-032'],
                ['name'=>'Mawukoenya Nutekpor','email'=>'mawukoenya.nutekpor@jsg.gov.gh','emp_id'=>'PM-033'],
                ['name'=>'Grace Linda Nyarko','email'=>'grace.nyarko@jsg.gov.gh','emp_id'=>'PM-034'],
                ['name'=>'Akua Oppong-Mensah','email'=>'akua.oppong-mensah@jsg.gov.gh','emp_id'=>'PM-035'],
                ['name'=>'Dzifa Azumah','email'=>'dzifa.azumah@jsg.gov.gh','emp_id'=>'PM-036'],
                ['name'=>'Bernice Mawusi Kpodo','email'=>'bernice.kpodo@jsg.gov.gh','emp_id'=>'PM-037'],
                ['name'=>'Josephine Akyaa Dwamena','email'=>'josephine.dwamena@jsg.gov.gh','emp_id'=>'PM-038'],
                ['name'=>'Alhassan Dramani','email'=>'alhassan.dramani@jsg.gov.gh','emp_id'=>'PM-039'],
                ['name'=>'Bernard Debrah Biney','email'=>'bernard.biney@jsg.gov.gh','emp_id'=>'PM-040'],
                ['name'=>'Derrick Annan','email'=>'derrick.annan@jsg.gov.gh','emp_id'=>'PM-041'],
                ['name'=>'Nelson Delasi Awuku','email'=>'nelson.awuku@jsg.gov.gh','emp_id'=>'PM-042'],
                ['name'=>'Simon Kofi Bediako','email'=>'simon.bediako@jsg.gov.gh','emp_id'=>'PM-043'],
                ['name'=>'Debora Gyaawa Donkor','email'=>'debora.donkor@jsg.gov.gh','emp_id'=>'PM-044'],
                ['name'=>'Nana Ama Dabbah Fynn','email'=>'nana.fynn@jsg.gov.gh','emp_id'=>'PM-045'],
                ['name'=>'Kwame Adjei Manu','email'=>'kwame.manu@jsg.gov.gh','emp_id'=>'PM-046'],
                ['name'=>'Prince Osei Owusu','email'=>'prince.owusu@jsg.gov.gh','emp_id'=>'PM-047'],
                ['name'=>'Siran Mahama','email'=>'siran.mahama@jsg.gov.gh','emp_id'=>'PM-048'],
                ['name'=>'Josephine Abigail Fosuaa Appiah','email'=>'josephine.appiah@jsg.gov.gh','emp_id'=>'PM-049'],
                ['name'=>'Nancy Teiko Searyoh','email'=>'nancy.searyoh@jsg.gov.gh','emp_id'=>'PM-050'],
                ['name'=>'Bianca Gyamera-Beeko','email'=>'bianca.gyamera-beeko@jsg.gov.gh','emp_id'=>'PM-051'],
                ['name'=>'Joseph Yennuban Kunsong','email'=>'joseph.kunsong@jsg.gov.gh','emp_id'=>'PM-052'],
                ['name'=>'Dora Nsiah Jackson','email'=>'dora.jackson@jsg.gov.gh','emp_id'=>'PM-053'],
                ['name'=>'Benedicta Antwi','email'=>'benedicta.antwi@jsg.gov.gh','emp_id'=>'PM-054'],
                ['name'=>'Kweku Ansah Akrofi','email'=>'kweku.akrofi@jsg.gov.gh','emp_id'=>'PM-055'],
                ['name'=>'Emmanuella Sarah Asmah','email'=>'emmanuella.asmah@jsg.gov.gh','emp_id'=>'PM-056'],
                ['name'=>'Bernice Oduro Kwarteng','email'=>'bernice.kwarteng@jsg.gov.gh','emp_id'=>'PM-057'],
                ['name'=>'Linda Fremah Adom Okyere','email'=>'linda.okyere@jsg.gov.gh','emp_id'=>'PM-058'],
                ['name'=>'Rosemary Abena Gyimah','email'=>'rosemary.gyimah@jsg.gov.gh','emp_id'=>'PM-059'],
                ['name'=>'Famous Yao Amanyo','email'=>'famous.amanyo@jsg.gov.gh','emp_id'=>'PM-060'],
                ['name'=>'Anita Sheila Serwaa Crabbe','email'=>'anita.crabbe@jsg.gov.gh','emp_id'=>'PM-061'],
                ['name'=>'Sylvia Afia Owusuaa','email'=>'sylvia.owusuaa@jsg.gov.gh','emp_id'=>'PM-062'],
                ['name'=>'Adwoa Benaso Asumadu-Sakyi','email'=>'adwoa.asumadu-sakyi@jsg.gov.gh','emp_id'=>'PM-063'],
                ['name'=>'Maame Yaa Amoakoa Kusi-Mensah','email'=>'maame.kusi-mensah@jsg.gov.gh','emp_id'=>'PM-064'],
                ['name'=>'Abigail Oppong','email'=>'abigail.oppong@jsg.gov.gh','emp_id'=>'PM-065'],
                ['name'=>'Victor Kusi','email'=>'victor.kusi@jsg.gov.gh','emp_id'=>'PM-066'],
                ['name'=>'Awurama Damoah Darkwah','email'=>'awurama.darkwah@jsg.gov.gh','emp_id'=>'PM-067'],
                ['name'=>'Adeline Owusua Asante','email'=>'adeline.asante@jsg.gov.gh','emp_id'=>'PM-068'],
                ['name'=>'Emmanuel Mawuli Ekuna','email'=>'emmanuel.ekuna@jsg.gov.gh','emp_id'=>'PM-069'],
                ['name'=>'Anna Akosua Appiaah Gottfried Anaafi Gyasi','email'=>'anna.gyasi@jsg.gov.gh','emp_id'=>'PM-070'],
                ['name'=>'Sherry Gollo','email'=>'sherry.gollo@jsg.gov.gh','emp_id'=>'PM-071'],
                ['name'=>'Eugenia Adubea Fordjour','email'=>'eugenia.fordjour@jsg.gov.gh','emp_id'=>'PM-072'],
                ['name'=>'Beatrice Boatemaa Damoah','email'=>'beatrice.damoah@jsg.gov.gh','emp_id'=>'PM-073'],
                ['name'=>'Nana Achiaa Buruwaa Ababioh','email'=>'nana.ababioh@jsg.gov.gh','emp_id'=>'PM-074'],
                ['name'=>'Mabel Naa Lamiley Ahele','email'=>'mabel.ahele@jsg.gov.gh','emp_id'=>'PM-075'],
                ['name'=>'Shirley Asante','email'=>'shirley.asante@jsg.gov.gh','emp_id'=>'PM-076'],
                ['name'=>'Maame Abena Dartey-Lartey','email'=>'maame.dartey-lartey@jsg.gov.gh','emp_id'=>'PM-077'],
                ['name'=>'Peter Kobblah Ametsowu','email'=>'peter.ametsowu@jsg.gov.gh','emp_id'=>'PM-078'],
                ['name'=>'Lucy Asafo-Adjei','email'=>'lucy.asafo-adjei@jsg.gov.gh','emp_id'=>'PM-079'],
                ['name'=>'Anastacia Yaa Agyeiwaa Karimu','email'=>'anastacia.karimu@jsg.gov.gh','emp_id'=>'PM-080'],
                ['name'=>'Bright Ajosagi Akoande','email'=>'bright.akoande@jsg.gov.gh','emp_id'=>'PM-081'],
                ['name'=>'Dromo Afarley Djarbeng','email'=>'dromo.djarbeng@jsg.gov.gh','emp_id'=>'PM-082'],
                ['name'=>'Jeroma Tawiah Owusu','email'=>'jeroma.owusu@jsg.gov.gh','emp_id'=>'PM-083'],
                ['name'=>'Claudia Naa Anorkai Akuokor Abbey','email'=>'claudia.abbey@jsg.gov.gh','emp_id'=>'PM-084'],
                ['name'=>'Melissa Selorm Dadson','email'=>'melissa.dadson@jsg.gov.gh','emp_id'=>'PM-085'],
                ['name'=>'Georgette Carmel Lutterodt','email'=>'georgette.lutterodt@jsg.gov.gh','emp_id'=>'PM-086'],
                ['name'=>'Josephine Valeen Akorfa Akpanya-Hlover','email'=>'josephine.akpanya-hlover@jsg.gov.gh','emp_id'=>'PM-087'],
                ['name'=>'Christian Mawusi Ntow','email'=>'christian.ntow@jsg.gov.gh','emp_id'=>'PM-088'],
                ['name'=>'Christabel Awo Tei Sasraku','email'=>'christabel.sasraku@jsg.gov.gh','emp_id'=>'PM-089'],
                ['name'=>'Stephen Tabiri','email'=>'stephen.tabiri@jsg.gov.gh','emp_id'=>'PM-090'],
                ['name'=>'Comfort Asamoah Sarpong','email'=>'comfort.sarpong@jsg.gov.gh','emp_id'=>'PM-091'],
                ['name'=>'Gloria Afua Kesewa Asamani','email'=>'gloria.asamani@jsg.gov.gh','emp_id'=>'PM-092'],
                ['name'=>'Juliana Millicent Ocran','email'=>'juliana.ocran@jsg.gov.gh','emp_id'=>'PM-093'],
                ['name'=>'Eric Kwarteng','email'=>'eric.kwarteng@jsg.gov.gh','emp_id'=>'PM-094'],
                ['name'=>'Emmanuel Wiafe Adu','email'=>'emmanuel.adu@jsg.gov.gh','emp_id'=>'PM-095'],
                ['name'=>'Jehoshaphat Achina Nyarko','email'=>'jehoshaphat.nyarko@jsg.gov.gh','emp_id'=>'PM-096'],
                ['name'=>'Eugene Obeng-Ntim','email'=>'eugene.obeng-ntim@jsg.gov.gh','emp_id'=>'PM-097'],
                ['name'=>'Iddi Adama','email'=>'iddi.adama@jsg.gov.gh','emp_id'=>'PM-098'],
                ['name'=>'Olivia Acquah-Dadzie','email'=>'olivia.acquah-dadzie@jsg.gov.gh','emp_id'=>'PM-099'],
                ['name'=>'George Wellington Arhin','email'=>'george.arhin@jsg.gov.gh','emp_id'=>'PM-100'],
                ['name'=>'Godson Etse Kumado','email'=>'godson.kumado@jsg.gov.gh','emp_id'=>'PM-101'],
                ['name'=>'Amy Bondzie-Hanson','email'=>'amy.bondzie-hanson@jsg.gov.gh','emp_id'=>'PM-102'],
                ['name'=>'Ama Benieh Kwaw-Swanzy','email'=>'ama.kwaw-swanzy@jsg.gov.gh','emp_id'=>'PM-103'],
                ['name'=>'Sandra Xorlali Lavison','email'=>'sandra.lavison@jsg.gov.gh','emp_id'=>'PM-104'],
                ['name'=>'Yvonne Nakie Nanor','email'=>'yvonne.nanor@jsg.gov.gh','emp_id'=>'PM-105'],
                ['name'=>'Yvonne Nelly Ama Adjadi','email'=>'yvonne.adjadi@jsg.gov.gh','emp_id'=>'PM-106'],
                ['name'=>'Lord Delvin Essandoh','email'=>'lord.essandoh@jsg.gov.gh','emp_id'=>'PM-107'],
                ],
            ],
            [
                'level'  => 'Senior Career Magistrate',
                'judges' => [
                ['name'=>'Stanislaus Amanoipo','email'=>'stanislaus.amanoipo@jsg.gov.gh','emp_id'=>'SCM-001'],
                ['name'=>'Samuel Entee','email'=>'samuel.entee@jsg.gov.gh','emp_id'=>'SCM-002'],
                ['name'=>'Lawrence Buenor Buer','email'=>'lawrence.buer@jsg.gov.gh','emp_id'=>'SCM-003'],
                ['name'=>'Iliasu Abdul Majid','email'=>'iliasu.majid@jsg.gov.gh','emp_id'=>'SCM-004'],
                ['name'=>'Sam Nibi Medjida','email'=>'sam.medjida@jsg.gov.gh','emp_id'=>'SCM-005'],
                ['name'=>'Joseph Mensah','email'=>'joseph.mensah@jsg.gov.gh','emp_id'=>'SCM-006'],
                ['name'=>'Charles Owusu-Nsiah','email'=>'charles.owusu-nsiah@jsg.gov.gh','emp_id'=>'SCM-007'],
                ['name'=>'Abdulai Abdul-Baki','email'=>'abdulai.abdul-baki@jsg.gov.gh','emp_id'=>'SCM-008'],
                ['name'=>'Albert Annor Owusu','email'=>'albert.owusu@jsg.gov.gh','emp_id'=>'SCM-009'],
                ['name'=>'Eric Baah Boateng','email'=>'eric.boateng@jsg.gov.gh','emp_id'=>'SCM-010'],
                ['name'=>'Clement Kwasi Asomah','email'=>'clement.asomah@jsg.gov.gh','emp_id'=>'SCM-011'],
                ['name'=>'Emmanuel Kwame Boadu','email'=>'emmanuel.boadu@jsg.gov.gh','emp_id'=>'SCM-012'],
                ['name'=>'Rhoda K. Donkor','email'=>'rhoda.donkor@jsg.gov.gh','emp_id'=>'SCM-013'],
                ['name'=>'Cynthia Adjei Andy','email'=>'cynthia.andy@jsg.gov.gh','emp_id'=>'SCM-014'],
                ['name'=>'Alice Afua Yirenkyi','email'=>'alice.yirenkyi@jsg.gov.gh','emp_id'=>'SCM-015'],
                ['name'=>'Rosemond Vera Aryeetey Ocloo','email'=>'rosemond.ocloo@jsg.gov.gh','emp_id'=>'SCM-016'],
                ['name'=>'Baba Issahaku Iddi','email'=>'baba.iddi@jsg.gov.gh','emp_id'=>'SCM-017'],
                ['name'=>'Joseph Hamidu Nasigre','email'=>'joseph.nasigre@jsg.gov.gh','emp_id'=>'SCM-018'],
                ['name'=>'Sydney Braimah','email'=>'sydney.braimah@jsg.gov.gh','emp_id'=>'SCM-019'],
                ['name'=>'Selorm Kuma Dzata','email'=>'selorm.dzata@jsg.gov.gh','emp_id'=>'SCM-020'],
                ['name'=>'Thomas Boadi Soyori','email'=>'thomas.soyori@jsg.gov.gh','emp_id'=>'SCM-021'],
                ['name'=>'Issah Abdul-Wahab','email'=>'issah.abdul-wahab@jsg.gov.gh','emp_id'=>'SCM-022'],
                ['name'=>'Janet Ahomka Yeboah','email'=>'janet.yeboah@jsg.gov.gh','emp_id'=>'SCM-023'],
                ['name'=>'Anthony Asaah','email'=>'anthony.asaah@jsg.gov.gh','emp_id'=>'SCM-024'],
                ['name'=>'Eunice Anamsibadeck Apaliwen','email'=>'eunice.apaliwen@jsg.gov.gh','emp_id'=>'SCM-025'],
                ['name'=>'Gifty Cudjoe','email'=>'gifty.cudjoe@jsg.gov.gh','emp_id'=>'SCM-026'],
                ['name'=>'Comfort Adimazoya Apalayine','email'=>'comfort.apalayine@jsg.gov.gh','emp_id'=>'SCM-027'],
                ['name'=>'Augustine Akusa-Am','email'=>'augustine.akusa-am@jsg.gov.gh','emp_id'=>'SCM-028'],
                ['name'=>'Naomi Akyiano','email'=>'naomi.akyiano@jsg.gov.gh','emp_id'=>'SCM-029'],
                ['name'=>'Stella Amedogbe','email'=>'stella.amedogbe@jsg.gov.gh','emp_id'=>'SCM-030'],
                ['name'=>'Alberta Amponsah','email'=>'alberta.amponsah@jsg.gov.gh','emp_id'=>'SCM-031'],
                ['name'=>'George Davies Kwesi Ofori','email'=>'george.ofori@jsg.gov.gh','emp_id'=>'SCM-032'],
                ['name'=>'Ernest Yao Agbenya','email'=>'ernest.agbenya@jsg.gov.gh','emp_id'=>'SCM-033'],
                ['name'=>'Yaw Agyare-Amoanpong Akosah','email'=>'yaw.akosah@jsg.gov.gh','emp_id'=>'SCM-034'],
                ['name'=>'Iddrisu Issah Kpeglah','email'=>'iddrisu.kpeglah@jsg.gov.gh','emp_id'=>'SCM-035'],
                ['name'=>'Peter Anongbare','email'=>'peter.anongbare@jsg.gov.gh','emp_id'=>'SCM-036'],
                ['name'=>'Derick Parden Eshun','email'=>'derick.eshun@jsg.gov.gh','emp_id'=>'SCM-037'],
                ['name'=>'Solomon Kwasi Alomatu','email'=>'solomon.alomatu@jsg.gov.gh','emp_id'=>'SCM-038'],
                ['name'=>'Ayagiba Salifu Bugri','email'=>'ayagiba.bugri@jsg.gov.gh','emp_id'=>'SCM-039'],
                ['name'=>'Emmanuel Davies','email'=>'emmanuel.davies@jsg.gov.gh','emp_id'=>'SCM-040'],
                ['name'=>'Emelia Kokora Abruquah','email'=>'emelia.abruquah@jsg.gov.gh','emp_id'=>'SCM-041'],
                ['name'=>'Felicia Gandedzi','email'=>'felicia.gandedzi@jsg.gov.gh','emp_id'=>'SCM-042'],
                ],
            ],
            [
                'level'  => 'Career Magistrate',
                'judges' => [
                ['name'=>'Joseph Akuoko','email'=>'joseph.akuoko@jsg.gov.gh','emp_id'=>'CM-001'],
                ['name'=>'Samuel Walker Essel','email'=>'samuel.essel@jsg.gov.gh','emp_id'=>'CM-002'],
                ['name'=>'Erasmus Narh Addo','email'=>'erasmus.addo@jsg.gov.gh','emp_id'=>'CM-003'],
                ['name'=>'Benjamin Attabra Bennet','email'=>'benjamin.bennet@jsg.gov.gh','emp_id'=>'CM-004'],
                ['name'=>'Francis Asakeya Ana-Am','email'=>'francis.ana-am@jsg.gov.gh','emp_id'=>'CM-005'],
                ['name'=>'Patience Ashami Ablor','email'=>'patience.ablor@jsg.gov.gh','emp_id'=>'CM-006'],
                ['name'=>'Victoria Akua Ghansah','email'=>'victoria.ghansah@jsg.gov.gh','emp_id'=>'CM-007'],
                ['name'=>'Paulina Kwakyewa Adwoa','email'=>'paulina.adwoa@jsg.gov.gh','emp_id'=>'CM-008'],
                ['name'=>'Florence A. Baah','email'=>'florence.baah@jsg.gov.gh','emp_id'=>'CM-009'],
                ['name'=>'Annie Adobor','email'=>'annie.adobor@jsg.gov.gh','emp_id'=>'CM-010'],
                ['name'=>'Love Sitsofe B. Mawuli-Woname','email'=>'love.mawuli-woname@jsg.gov.gh','emp_id'=>'CM-011'],
                ['name'=>'Kojo Frimpong Manso','email'=>'kojo.manso@jsg.gov.gh','emp_id'=>'CM-012'],
                ['name'=>'Edward Essel','email'=>'edward.essel@jsg.gov.gh','emp_id'=>'CM-013'],
                ['name'=>'Augustine Fiifi Domful','email'=>'augustine.domful@jsg.gov.gh','emp_id'=>'CM-014'],
                ['name'=>'Joseph Baah-Ansah','email'=>'joseph.baah-ansah@jsg.gov.gh','emp_id'=>'CM-015'],
                ['name'=>'Grace Osei','email'=>'grace.osei@jsg.gov.gh','emp_id'=>'CM-016'],
                ['name'=>'Magdalene Thompson','email'=>'magdalene.thompson@jsg.gov.gh','emp_id'=>'CM-017'],
                ['name'=>'Maxwell Maxibrian Titriku','email'=>'maxwell.titriku@jsg.gov.gh','emp_id'=>'CM-018'],
                ['name'=>'Edith Lucy Dzormeku','email'=>'edith.dzormeku@jsg.gov.gh','emp_id'=>'CM-019'],
                ['name'=>'Rejoice Aseye Gadagoe','email'=>'rejoice.gadagoe@jsg.gov.gh','emp_id'=>'CM-020'],
                ],
            ],
        ];

        $totalNew     = 0;
        $totalUpdated = 0;
        $totalSkipped = 0;

        foreach ($courtLevels as $levelData) {
            $level    = $levelData['level'];
            $levelNew = $levelUpd = 0;

            $this->command->info("\n  [$level]");

            foreach ($levelData['judges'] as $j) {
                try {
                    $exists = User::where('email', $j['email'])->exists();

                    $user = User::updateOrCreate(
                        ['email' => $j['email']],
                        [
                            'name'                   => $j['name'],
                            'password'               => Hash::make('Jsg@Judge2025!'),
                            'employee_id'            => $j['emp_id'],
                            'position'               => $level,
                            'department'             => 'Judiciary',
                            'role_id'                => 6,
                            'is_active'              => true,
                            'is_approved'            => true,
                            'approved_at'            => now(),
                            'status'                 => 'active',
                            'require_password_reset' => 'yes',
                        ]
                    );

                    $user->syncRoles(['judge']);

                    $exists ? $levelUpd++ : $levelNew++;
                } catch (\Exception $e) {
                    $this->command->warn("    SKIP {$j['name']}: " . $e->getMessage());
                    $totalSkipped++;
                }
            }

            $this->command->info("    New: $levelNew  Updated: $levelUpd");
            $totalNew     += $levelNew;
            $totalUpdated += $levelUpd;
        }

        $grand = $totalNew + $totalUpdated;
        $this->command->info("\n==============================================");
        $this->command->info("Judge / Magistrate Seeding — Final Summary");
        $this->command->info("New records   : $totalNew");
        $this->command->info("Updated       : $totalUpdated");
        $this->command->warn("Skipped       : $totalSkipped");
        $this->command->info("Grand Total   : $grand / 448");
        $this->command->info("==============================================\n");
    }
}
